### ISSUE TITLE
Not an issue

### ISSUE THREAD

**Issue by AndreMPCosta** [kevin-keraudren/randomforest-python#1]
Any way to save the trained model and load it afterwards?

**Comment by kevin-keraudren** [comment]
Yes you can, I fixed the code that does it and added it to the examples: https://github.com/kevin-keraudren/randomforest-python/commit/8ec24c5d9ac8577d411402da87385ad9db6f5001

**Comment by AndreMPCosta** [comment]
That is awesome, many thanks Kevin! I was looking for a pure Python implementation since I need to use it on an Android Phone, and there aren't many alternatives to scikit-learn. Until I stumbled upon your code!

**Comment by kevin-keraudren** [comment]
As a side note, you could have considered the `pickle` module (https://docs.python.org/3/library/pickle.html), or `joblib.dump`/`joblib.load` (https://pythonhosted.org/joblib/generated/joblib.dump.html).

**Comment by AndreMPCosta** [comment]
There is no regression model right? :(

**Comment by kevin-keraudren** [comment]
No, there isn't.

**Comment by kevin-keraudren** [comment]
Now there is.

**Comment by AndreMPCosta** [comment]
Thanks Kevin! :)
